### ISSUE TITLE
Guillotine silently fails when this input type is in your app

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-guillotine#75]
Basically, everything is working fine, but this does not show up in schema somhow?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<content-type xmlns="urn:enonic:xp:model:1.0">
  <display-name>Person</display-name>
  <super-type>base:structured</super-type>
  <form>
    <input type="ImageSelector" name="phoTos">
      <label>Photos</label>
      <occurrences minimum="0" maximum="0"/>
    </input>
    <input type="TextArea" name="photos">
      <label>Bio</label>
       <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="Date" name="date_of_birth">
      <label>Birth Date</label>
       <occurrences minimum="0" maximum="1"/>
    </input>
    <input type="HtmlArea" name="document">
      <label>Document</label>
       <occurrences minimum="0" maximum="1"/>
    </input>    
  </form>
</content-type>
```

**Comment by anatol-sialitski** [comment]
Hi @sigdestad,

Could you please provide details about the version of the Guillotine which you use? 
I can not reproduce that locally. I tested it on 4.2.1 and above

![image](https://user-images.githubusercontent.com/53557255/102190561-414f5980-3ec9-11eb-8689-08981275cf99.png)

**Comment by sigdestad** [comment]
I was probably using the HMDB application. As you can se from the names, I was probably modifying the base content type that comes with the application.

Try using the app as a starter and doing the same modifications after deploying it the first time?

**Comment by anatol-sialitski** [comment]
I use the hmdb app too, But I can not reproduce it.
![image](https://user-images.githubusercontent.com/53557255/102205395-30f4aa00-3edc-11eb-8072-cada46cb1774.png)

**Comment by sigdestad** [comment]
Ok, lets close the task then

**Comment by anatol-sialitski** [comment]
@sigdestad @alansemenov 

I looked into that issue a little bit more and I want to summary the following things:

- Guillotine generates the both fields `photos` and `phoTos` based on the `person.xml` file correctly.
- The HMDB application generates Person nodes in repo with the `photos` property (ref to node with attachment) in the `data`  on start if `hmdb` repo is empty. 
- If we change the `person.xml` as in the bug's description, then the `photos` property will have string type. Once GraphQL query will be called then `photos` will be returned as a reference on an attachment as string and the `phoTos` property will be returned as empty array for all nodes which do not have this property, otherwise we will see a `ResourceProblemException`.

I think that this behavior is correct.

In order to avoid that issue we can change the `person.xml` by adding a new input item with name `phoTos` with the `TextArea` type instead of rename of existing input item.

**Comment by sigdestad** [comment]
Is this content type actually working inside content studio?

**Comment by sigdestad** [comment]
I mean, does node api support two fields on same level where only case is different?

**Comment by sigdestad** [comment]
Generally, I would think that this should not be working?

**Comment by anatol-sialitski** [comment]
@sigdestad Yes, looks like Node API supports that
![image](https://user-images.githubusercontent.com/53557255/102473278-53b3c980-4068-11eb-946d-fb16fa3dfb97.png)

**Comment by sigdestad** [comment]
But, it is basically not working when using content studio?

**Comment by anatol-sialitski** [comment]
What you mean? I able to create/edit a content using Content Studio and find them via Guillotine.

**Comment by sigdestad** [comment]
So, it actually works. Both in Content Studio, node API and finally in GraphQL. What about query language? Does it differentiate between capital case and not?

**Comment by anatol-sialitski** [comment]
it works
![image](https://user-images.githubusercontent.com/53557255/102480388-3fc09580-4071-11eb-9b4a-071639a814dc.png)

**Comment by sigdestad** [comment]
Ok, then everything is sweet I guess? :-) 👍

**Comment by anatol-sialitski** [comment]
I guess yes!
